allowBuilds:
  esbuild: true
catalogMode: "strict"
catalogs:
  dependencies:
    vue: 3.5.41
  devDependencies:
    node: runtime:26.7.0
    vite: 8.2.2
    vite-plugin-cem: 0.8.5
    vite-plugin-cp: 8.0.0
    vite-plugin-dts: 5.0.3
    vite-plugin-lit-css: 3.0.0
    vite-plugin-pwa: 1.3.0
    vite-plugin-svgo: 3.0.1
    vite-plugin-version-mark: 0.2.2
    vite-plus: 0.2.9
    vitepress: 1.6.4
  typescript:
    typescript: "npm:@typescript/typescript6@6.0.2"
    typescript7: "npm:typescript@7.0.2"
color: "always"
configDependencies:
  "@pnpm/plugin-types-fixer": 0.1.0
dedupeDirectDeps: true
dedupeInjectedDeps: true
dedupePeerDependents: true
dedupePeers: true
engineStrict: false
extendNodePath: true
gitChecks: true
hoist: true
hoistWorkspacePackages: true
includeWorkspaceRoot: true
linkWorkspacePackages: "deep"
lockfile: true
loglevel: "debug"
managePackageManagerVersions: true
minimumReleaseAgeExclude:
  - vite@6.4.3
  - nanoid@3.3.18
nodeVersion: "26.7.0"
overrides:
  nanoid@<3.3.18: ^3.3.18
  vite@<=6.4.2: ^6.4.3
packageManagerStrictVersion: true
preferWorkspacePackages: true
recursiveInstall: true
resolutionMode: "time-based"
resolvePeersFromWorkspaceRoot: true
saveExact: true
savePrefix: ""
saveWorkspaceProtocol: "rolling"
scriptShell: "zsh"
sharedWorkspaceLockfile: true
updateNotifier: true
useNodeVersion: "26.7.0"
